{
 "title": "Downstairs HVAC Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HVAC Operating State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "HVAC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "thermostatOperatingState",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermostat" }
     ]
    },
    {
     "alias": "2nd Stage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Thermostat 2nd Stage Status"
      }
     ]
    },
    {
     "alias": "HVAC Fan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "thermostatFanMode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermostat" }
     ]
    },
    {
     "alias": "Fan State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "thermostatFanState",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermostat" }
     ]
    },
    {
     "alias": "Dehum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "condition": "OR",
       "key": "displayName",
       "operator": "=",
       "value": "Dining Room Dehumidifying Statistics"
      },
      {
       "condition": "OR",
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Dehumidifying Statistics"
      }
     ]
    },
    {
     "alias": "Dehum Fan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "displayName",
       "operator": "=",
       "value": "Dining Room Dehumidifier Fan Status"
      },
      {
       "condition": "OR",
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Dehumidifier Fan Status"
      }
     ]
    },
    {
     "alias": "Sensation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermal Comfort" }
     ]
    }
   ]
  },
  {
   "title": "Downstairs Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Dewpoint" }
     ]
    },
    {
     "alias": "High Setpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Dewpoint Setpoint" }
     ]
    },
    {
     "alias": "Dehumidifying",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "valueState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "condition": "OR",
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Dehumidifying Statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstairs Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Average Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Average Humidity" }
     ]
    },
    {
     "alias": "Dehumidifying",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "valueState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "condition": "OR",
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Dehumidifying Statistics"
      }
     ]
    },
    {
     "alias": "High Setpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Humidity Setpoint" }
     ]
    }
   ]
  },
  {
   "title": "Downstairs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Average Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Average Temperature" }
     ]
    },
    {
     "alias": "Tstat Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE (\"deviceId\" = '4139') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermostat" }
     ]
    },
    {
     "alias": "Cooling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "valueState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Cooling Statistics" }
     ]
    },
    {
     "alias": "Heating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch",
     "select": [
      [
       { "params": [ "valueState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Heating Statistics" }
     ]
    },
    {
     "alias": "Tstat Setpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "thermostatSetpoint",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE (\"deviceId\" = '4139') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Downstairs Thermostat" }
     ]
    }
   ]
  },
  {
   "title": "Dehumidifier Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "displayName",
       "operator": "=",
       "value": "Downstairs Dehumidifier Power Outlet"
      }
     ]
    }
   ]
  }
 ]
}